package br.ufes.informatica.ufespay.core.application;

import java.io.Serializable;

import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface CommentService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public Comment createComment(int idTransaction, String comment);

	/** TODO: generated by FrameWeb. Should be documented. */
	public void deleteComment(int idComment);

}