package br.ufes.informatica.ufespay.core.domain;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Comment extends PersistentObjectSupport implements Comparable<Comment> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String text;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private User author;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	public int id;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	private Transactions Source;

	/** Getter for text. */
	public String getText() {
		return text;
	}

	/** Setter for text. */
	public void setText(String text) {
		this.text = text;
	}

	/** Getter for author. */
	public User getAuthor() {
		return author;
	}

	/** Setter for author. */
	public void setAuthor(User author) {
		this.author = author;
	}

	/** Getter for id. */
	public int getId() {
		return id;
	}

	/** Setter for id. */
	public void setId(int id) {
		this.id = id;
	}

	/** Getter for Source. */
	public Transactions getSource() {
		return Source;
	}

	/** Setter for Source. */
	public void setSource(Transactions Source) {
		this.Source = Source;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Comment o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}