package br.ufes.informatica.ufespay.core.domain;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Wallet extends PersistentObjectSupport implements Comparable<Wallet> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private Float value;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	public int id;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToOne(mappedBy = "Target")
	private User Source;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToMany(mappedBy = "Source")
	private Set<Transactions> Target;

	/** Getter for value. */
	public Float getValue() {
		return value;
	}

	/** Setter for value. */
	public void setValue(Float value) {
		this.value = value;
	}

	/** Getter for id. */
	public int getId() {
		return id;
	}

	/** Setter for id. */
	public void setId(int id) {
		this.id = id;
	}

	/** Getter for Source. */
	public User getSource() {
		return Source;
	}

	/** Setter for Source. */
	public void setSource(User Source) {
		this.Source = Source;
	}

	/** Getter for Target. */
	public Set<Transactions> getTarget() {
		return Target;
	}

	/** Setter for Target. */
	public void setTarget(Set<Transactions> Target) {
		this.Target = Target;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Wallet o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}