package br.ufes.informatica.ufespay.core.persistence;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface CommentDAO extends BaseDAO<Comment> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public Comment createComment(int idTransaction, String comment);

	/** TODO: generated by FrameWeb. Should be documented. */
	public void deleteComment(int idComment);

}