package br.ufes.informatica.ufespay.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.ufespay.core.persistence.CommentDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class CommentServiceBean implements CommentService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private CommentDAO commentDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Comment createComment(int idTransaction, String comment) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void deleteComment(int idComment) {
		// FIXME: auto-generated method stub
		return;
	}

}